[package]
version = "1.2.0"
category = "Simulation"
title = "ROS 2 UI Components"
description = "This extension provides UI components for ROS 2 integration with Isaac Sim."
keywords = ["isaac", "ROS2", "UI"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.asset.browser" = {}
"isaacsim.core.utils" = {}
"isaacsim.gui.components" = {}
"isaacsim.ros2.nodes" = {}
"isaacsim.storage.native" = {}
"omni.graph" = {}
"omni.graph.tools" = {}
"omni.kit.menu.utils" = {}
"omni.kit.notification_manager" = {}
"omni.kit.uiapp" = {}
"omni.kit.window.extensions" = {}
"omni.timeline" = {}
"omni.ui" = {}

[[python.module]]
name = "isaacsim.ros2.ui"

[fswatcher.patterns]
include = ["*.ogn", "*.py", "*.toml"]
exclude = ["Ogn*Database.py"]

[fswatcher.paths]
exclude = ["*/bin", "*/__pycache__/*", "*/.git/*"]

[[test]]
dependencies = [
    "omni.isaac.ml_archive",
]
args = [
    "--enable",
    "omni.kit.loop-isaac",
    "--reset-user",
    "--vulkan",
    "--/app/asyncRendering=0",
    "--/app/asyncRenderingLowLatency=0",
    "--/app/fastShutdown=1",
    "--/app/file/ignoreUnsavedOnExit=1",
    "--/app/hydraEngine/waitIdle=0",
    "--/app/player/useFixedTimeStepping=false",
    "--/app/renderer/skipWhileMinimized=0",
    "--/app/renderer/sleepMsOnFocus=0",
    "--/app/renderer/sleepMsOutOfFocus=0",
    "--/app/runLoops/main/manualModeEnabled=true",
    "--/app/runLoops/main/rateLimitEnabled=false",
    "--/app/settings/fabricDefaultStageFrameHistoryCount=3",
    "--/app/settings/persistent=0",
    "--/app/useFabricSceneDelegate=true",
    "--/app/viewport/createCameraModelRep=0",
    "--/crashreporter/skipOldDumpUpload=1",
    "--/exts/omni.usd/locking/onClose=0",
    "--/omni/kit/plugin/syncUsdLoads=1",
    "--/omni/replicator/asyncRendering=0",
    '--/persistent/app/stage/upAxis="Z"',
    "--/persistent/app/viewport/defaults/tickRate=120",
    "--/persistent/app/viewport/displayOptions=31951",
    "--/persistent/omni/replicator/captureOnPlay=1",
    "--/persistent/omnigraph/updateToUsd=0",
    "--/persistent/physics/visualizationDisplayJoints=0",
    "--/persistent/renderer/startupMessageDisplayed=1",
    "--/persistent/simulation/defaultMetersPerUnit=1.0",
    "--/persistent/simulation/minFrameRate=15",
    "--/renderer/multiGpu/autoEnable=0",
    "--/renderer/multiGpu/enabled=0",
    "--/rtx-transient/dlssg/enabled=0",
    "--/rtx-transient/resourcemanager/enableTextureStreaming=1",
    "--/rtx/descriptorSets=360000",
    "--/rtx/hydra/enableSemanticSchema=1",
    "--/rtx/hydra/materialSyncLoads=1",
    "--/rtx/materialDb/syncLoads=1",
    "--/rtx/newDenoiser/enabled=1",
    "--/rtx/reservedDescriptors=900000",
]

stdoutFailPatterns.exclude = [
    '*The NumPy module was reloaded*',
]

[[test]]
name = "startup"
dependencies = [
    "omni.isaac.ml_archive",
]
args = [
    "--/app/settings/fabricDefaultStageFrameHistoryCount=3",
]

stdoutFailPatterns.exclude = [
    '*The NumPy module was reloaded*',
]
