[package]
version = "1.1.3"
category = "Simulation"
title = "Lula Test Widget"
description = "Run Simple Tests Using Lula Algorithms"
keywords = ["isaac", "lula"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.api" = {}
"isaacsim.gui.components" = {}
"isaacsim.robot_motion.lula" = {}
"isaacsim.robot_motion.motion_generation" = {}
"omni.kit.uiapp" = {}
"omni.physics" = {}
"omni.physics.physx" = {}

[[python.module]]
name = "isaacsim.robot_motion.lula_test_widget"

[[test]]
dependencies = [
    "omni.isaac.ml_archive",
]

stdoutFailPatterns.exclude = [    
    '*The NumPy module was reloaded*',
]

[[test]]
name = "startup"
dependencies = [
    "omni.isaac.ml_archive",
]

stdoutFailPatterns.exclude = [    
    '*The NumPy module was reloaded*',
]
