########################################################################################################################
# Example:
########################################################################################################################

#
# [[dependency]]                           # Toml way to define array of objects.
# python = "../_build/target-deps/python"  # Path to python used to install. Absolute or relative to this config.
# packages = ["numpy"]                     # Array of packages to install, they all will be passed directly to pip.
# target = "../_build/target-deps/numpy"   # Folder to install into.   Absolute or relative to this config.
# platforms = ["windows-x86_64"]           # Platform(s) to filter, default is ["*"].
# download_only = true                     # Do pip download instead of install, gets a whl file that can be installed later.

# !!!
# IMPORTANT: If you change this config cleanup target folder. Script check that it already exists and does nothing.

# Options.
# Various options are available that are passed through pip during the installation.

# download_only: Only download the pip package, do not install it.
# install_dependencies: When set to False, dependencies of a pip package will not be downloaded or installed
# append_to_install_folder: When set to true and the target directory already exists, these packages will be appended to the existing folder.
# build_isolated: Sets `--isolated` for pip install when installing. This means that environment variables and user settings will be ignored.
# add_python_to_lib_path: Will set --global-options to include Python's lib and include folders when running the pip install.
#    Useful when a python pip package has a C extension that needs to bind to Python. Setting this to true will set build_isolated to False.

########################################################################################################################
# Dependencies:
########################################################################################################################

# For newer version of pip we bundle only wheel files, to be installed at runtime upon first usage.
# Disabled because we get this with the base omni.kit.pip_archive extension
# [[dependency]]
# python = "../_build/target-deps/python"
# packages = ["pip==23.0.1"]
# target = "../_build/target-deps/pip_archive"
# platforms = ["*-x86_64"]
# download_only = true

# For many other pip packages used by default we install them in `pip_prebundle` folder to make available without need to install immediately.

# NOTE - For any new packages added to this list, please make sure that the license is compatible with Omniverse (i.e. avoid GPL/LGPL) and
# that a SWIPAT bug report is filed for legal to validate if there is no existing ticket.
# The SWIPAT template is here: http://nvbugs/2732212
# Dependencies for aiohttp should not be installed by default as we do not want to pull in chardet due to its license. Use cchardet instead

# Target kit 109.x
[[dependency]]
python = "../_build/target-deps/python"
packages = [
    "llvmlite==0.42.0",             # SWIPAT filed under: https://nvbugs/3433740 # Used by: (dependency of numba)
    "nest_asyncio==1.5.6",          # SWIPAT filed under: https://nvbugs/3433748 # Used by: isaacsim.ros2.sim_control, isaacsim.simulation_app
    "matplotlib==3.10.3",           # SWIPAT filed under: https://nvbugs/3430500 # Used by: isaacsim.sensors.rtx
    "contourpy==1.3.1",             # SWIPAT filed under: https://nvbugs/5303073 # Used by: (dependency of matplotlib)
    "fonttools==4.55.3",            # SWIPAT filed under: https://nvbugs/5303095 # Used by: (dependency of matplotlib)
    "pyparsing==3.0.9",             # SWIPAT filed under: https://nvbugs/3433756 # Used by: (dependency of matplotlib)
    "cycler==0.11.0",               # SWIPAT filed under: https://nvbugs/3433763 # Used by: (dependency of matplotlib)
    "kiwisolver==1.4.5",            # SWIPAT filed under: https://nvbugs/3433770 # Used by: (dependency of matplotlib)
    "packaging==23.0",              # SWIPAT filed under: https://nvbugs/3433815 # Used by: isaacsim.asset.exporter.urdf, isaacsim.ros2.bridge, isaacsim.ros2.core
    "osqp==0.6.7.post3",            # SWIPAT filed under: https://nvbugs/3577752 # Used by: isaacsim.robot.wheeled_robots
    "qdldl==0.1.7.post5",           # SWIPAT filed under: https://nvbugs/3577749 # Used by: (dependency of osqp)
    "pyperclip==1.8.0",             # SWIPAT filed under: https://nvbugs/5326856 # Used by: isaacsim.app.about, isaacsim.asset.importer.urdf, isaacsim.gui.components, isaacsim.robot_setup.gain_tuner
    "python-dateutil==2.9.0.post0", # SWIPAT filed under: https://nvbugs/5303032 # Used by: (dependency of aiobotocore, botocore, matplotlib)
    "six==1.17.0",                  # SWIPAT filed under: https://nvbugs/5303087 # Used by: (dependency of azure-core, azure-identity, isodate, python-dateutil)
]

target = "../_build/target-deps/isaac_core_prebundle"
platforms = ["*-x86_64", "*-aarch64"]
download_only = false
install_dependencies = false
append_to_install_folder = true
gather_licenses_path = "../_build/PACKAGE-LICENSES/PIP-prebundled-LICENSES.txt"
