# Target kit 109.x, python 3.12
# the scene converter is a python tool created by the SRL to export USD to URDF
[[dependency]]
python = "../_build/target-deps/python"
packages = [
    "lxml==6.0.2",                   # SWIPAT filed under: https://nvbugs/4248625 # Used by: isaacsim.asset.exporter.urdf
    "nvidia-srl-base==1.3.0",        # SWIPAT filed under: https://nvbugs/4235578 # Used by: (dependency of nvidia-srl-math, nvidia-srl-usd, nvidia-srl-usd-to-urdf)
    "nvidia-srl-math==1.0.0",        # SWIPAT filed under: https://nvbugs/4235574 # Used by: (dependency of nvidia-srl-usd, nvidia-srl-usd-to-urdf)
    "nvidia-srl-usd==2.0.0",         # SWIPAT filed under: https://nvbugs/4235568 # Used by: (dependency of nvidia-srl-usd-to-urdf)
    "nvidia-srl-usd-to-urdf==1.0.2", # SWIPAT filed under: https://nvbugs/4235566 # Used by: isaacsim.asset.exporter.urdf
    "setuptools_scm==8.2.0",         # SWIPAT filed under: https://nvbugs/4248640 # Used by: isaacsim.asset.exporter.urdf
]
target = "../_build/target-deps/isaac_usd_to_urdf_prebundle"
platforms = ["*-x86_64", "*-aarch64"]
download_only = false
install_dependencies = false
append_to_install_folder = true
gather_licenses_path = "../_build/PACKAGE-LICENSES/PIP-prebundled-LICENSES.txt"
extra_args = ["--extra-index-url", "https://pypi.org/simple"]