[package]
version = "1.1.7"
category = "Simulation"
title = "Isaac Sim Physics API Editor"
description = "Provides a UI tool for applying and removing physics APIs (collision, rigid body, articulation) on USD prims with support for convex hull and triangle mesh collision shapes."
keywords = ["isaac", "physics", "utils",]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.gui.components" = {}
"omni.physx" = {}

[[python.module]]
name = "isaacsim.util.physics"

[[python.module]]
name = "isaacsim.util.physics.tests"
