isaacsim.replicator.agent:
  version: 1.0.1
  simulation_duration: 60
  environment:
    base_stage_asset_path: "Isaac/Environments/Simple_Warehouse/full_warehouse.usd"
  sensor:
    groups:
      ceiling_cameras:
        num: 6
        aim_at_targets:
          distance_range: [5, 10]
          height_range: [7, 10]
          focal_length_range: [10, 15]
          look_down_angle_range: [30, 45]
  character:
    groups:
      warehouse_workers:
        asset_path: "Isaac/People/Characters/"
        num: 10
        routines:
          - wander:
              weight: 1
              repeat: 1
              walk:
                speed_range: [0.8, 1.5]
                distance_range: [5.0, 10.0]
              idle:
                - animation: idle
                  weight: 1
                  time_range: [2.0, 5.0]
  replicator:
    writers:
      IRABasicWriter:
        rgb: true
        camera_params: true
        object_info_bounding_box_2d_tight: true
        object_info_bounding_box_2d_loose: true
        object_info_bounding_box_3d: true
