# Extension configuration file.
# Visit the "Extension configuration file (extension.toml)" section for more details:
# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html
#

[package]
version = "0.1.1"
category = "Simulation"
title = "Motion Generation Tutorials"
description = "Tutorials for using the Lula planning library under motion generation."
keywords = ["lula","motion","generation","rmp","rmpflow","flow","rrt","trajectory"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"isaacsim.core.experimental.objects" = {}
"isaacsim.core.prims" = {}
"isaacsim.core.utils" = {}
"isaacsim.examples.extension" = {}
"isaacsim.gui.components" = {}
"isaacsim.robot_motion.lula" = {}
"isaacsim.robot_motion.motion_generation" = {}
"isaacsim.storage.native" = {}
"omni.physx" = {}
"omni.timeline" = {}
"omni.ui" = {}
"omni.usd" = {}

[[python.module]]
name = "isaacsim.robot_motion.motion_generation.tutorials.rmp_flow"

[[python.module]]
name = "isaacsim.robot_motion.motion_generation.tutorials.rrt"

[[python.module]]
name = "isaacsim.robot_motion.motion_generation.tutorials.kinematics"

[[python.module]]
name = "isaacsim.robot_motion.motion_generation.tutorials.trajectory_generator"

[[test]]
dependencies = [
    "omni.isaac.ml_archive",
]

[[test]]
name = "startup"
dependencies = [
    "omni.isaac.ml_archive",
]