[package]
version = "1.4.1"
category = "Simulation"
title = "Isaac Sim USD to URDF exporter"
description = "Extension that exports USD files to URDF"
keywords = ["isaac", "URDF"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true
writeTarget.platform = true # pip prebundle makes this extension os specific

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.gui.components" = {}
"omni.kit.pip_archive" = {}

[[python.module]]
path = "pip_prebundle"

[[python.module]]
name = "isaacsim.asset.exporter.urdf"

[[python.module]]
name = "isaacsim.asset.exporter.urdf.tests"

[[test]]
timeout = 400
dependencies = [
    "isaacsim.asset.importer.urdf",
    "isaacsim.core.experimental.prims",
    "isaacsim.storage.native",
]
stdoutFailPatterns.exclude = [
    "*Missing call to destroyResourceBindingSignature()*",
    '*not added to `TransformGraph` because it is not a link type or joint type prim.*',
    '*UserWarning: Sum of `faceVertexCounts` (392550) does not equal sum of length of `GeomSubset` `indices` (41287)*',
    '*Converted USD to URDF.*',
    '*Invalid Imu sensor prim*',
    '*not added to `TransformGraph` because it is not a link type or joint type prim.*',
    '*parent prim is missing contact report API*',
    '*Error processing node attribute `outputs:pointInstanceDataType`: dataType attribute is empty*'
]

[[test]]
name = "startup"
dependencies = [
    "omni.isaac.core_archive",
]
