[package]
version = "2.2.0"
category = "Simulation"
title = "Heightmap extension for Isaac Sim Occupancy Map"
description = "The Heightmap extension converts heightmap images into 3D terrain environments"
keywords = ["isaac", "occupancy map"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.core.experimental.utils" = {}
"isaacsim.gui.components" = {}
"omni.kit.uiapp" = {}
"omni.kit.viewport.window" = {}

[[python.module]]
name = "isaacsim.asset.importer.heightmap"
